name: CD - Publish for Blazor / FluentUI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    if: contains('nicholasrice,awentzel,eisenbergeffect', github.actor)

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: 
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: # optional
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: # optional
        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: # optional
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: # optional, default is true
        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: # optional, default is v*
        # API key to authenticate with NuGet server
        NUGET_KEY: # optional
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: # optional, default is https://api.nuget.org
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: # optional
